title: "Rober TF"
description: "Lorem Ipsum"
# date_format: "%B %d, %Y"
# permalink: "pretty"
# lang: "en"
# exclude: ['node_modules', "README.md", "package.json", "*.lock", ".idea", "Gemfile", "build", "misc", "assets", "tasks", "Makefile"]
